// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzptdn6VXa6bySmAqQYvP4PbB5yxfNMms',
    appId: '1:707108949559:web:5cb1aa566d488af05379b2',
    messagingSenderId: '707108949559',
    projectId: 'ditonton-ee874',
    authDomain: 'ditonton-ee874.firebaseapp.com',
    storageBucket: 'ditonton-ee874.appspot.com',
    measurementId: 'G-CKES9EVYBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ATl5kZ9JvoWqbWfL8Rdq_coOFaDy60I',
    appId: '1:707108949559:android:a897698c8d25021f5379b2',
    messagingSenderId: '707108949559',
    projectId: 'ditonton-ee874',
    storageBucket: 'ditonton-ee874.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBreGqoM8yC6MBsNeIJuBafMrJheHAxAsU',
    appId: '1:707108949559:ios:2063f6e1ccbd72795379b2',
    messagingSenderId: '707108949559',
    projectId: 'ditonton-ee874',
    storageBucket: 'ditonton-ee874.appspot.com',
    iosBundleId: 'com.example.ditonton',
  );
}
